# See http://www.appveyor.com/docs/appveyor-yml for many more options

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message
skip_commits:
  message: /updated readme.*/

install:
  - cinst pester

build: false

test_script:
# Test with native PS version, finalize
  - ps: . .\GithubConnect\githubconnect.Tests.ps1 -Test -Finalize

#deploy_script:
#  - ps: Get-Content .\Artifacts.txt | Foreach-Object { Push-AppveyorArtifact $_ }